--- 
- hosts: {{ instance_name }} 
  gather_facts: False 
  connection: ssh 
  user: ubuntu 
  sudo: yes 
  tasks: 
  vars:
    - tenant_message: "{{ tenant_message }}"
 
 # - name: write message
 #   shell: echo "{{ tenant_message }}" > /var/tmp/index.html
