---
- name: Copy templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ source_path }}/{{ item }}"
  with_items:
    - vbfd.conf
    - vbsm_cfg.txt

- name: Run make_certs.sh command
  shell: "./make_certs.sh mme {{ realm }}"
  args:
    chdir: "{{ source_path }}"

- name: Kill running MME
  shell: "killall -w {{ item }}"
  ignore_errors: yes
  with_items:
    - tmux
    - vb_acc

# vb_acc exits if it's not run with a TTY (?)
- name: Run MME
  shell: tmux new -d 'while true; do ./vb_acc >> /tmp/vb_acc.output 2>&1; sleep 15; done'
  args:
    chdir: "{{ source_path }}"
