---
- name: Copy templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ source_path }}/{{ item }}"
  with_items:
    - vbfd.conf
    - vbsm_cfg.txt

- name: Run make_certs.sh command
  shell: "./make_certs.sh mme {{ realm }}"
  args:
    chdir: "{{ source_path }}"

- name: Run vb_acc
  shell: "./vb_acc"
  args:
    chdir: "{{ source_path }}"
